/**
 * Promtube Backend API
 * The API for Promtube
 *
 * OpenAPI spec version: 0.0.1
 * Contact: horahora1567@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ArchiveEvents200ResponseInner {
    'videoUrl'?: string;
    'parnetUrl'?: string;
    'message'?: string;
    'timestamp'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "videoUrl",
            "baseName": "VideoUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "parnetUrl",
            "baseName": "ParnetUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "Message",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "Timestamp",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ArchiveEvents200ResponseInner.attributeTypeMap;
    }

    public constructor() {
    }
}

