/**
 * Promtube Backend API
 * The API for Promtube
 *
 * OpenAPI spec version: 0.0.1
 * Contact: horahora1567@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ArchiveRequests200ResponseInner {
    'userID'?: number;
    'url'?: string;
    'archivedVideos'?: number;
    'currentTotalVideos'?: number;
    'lastSynced'?: string;
    'backoffFactor'?: number;
    'downloadID'?: number;
    'undownloadableVideos'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userID",
            "baseName": "UserID",
            "type": "number",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "Url",
            "type": "string",
            "format": ""
        },
        {
            "name": "archivedVideos",
            "baseName": "ArchivedVideos",
            "type": "number",
            "format": ""
        },
        {
            "name": "currentTotalVideos",
            "baseName": "CurrentTotalVideos",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastSynced",
            "baseName": "LastSynced",
            "type": "string",
            "format": ""
        },
        {
            "name": "backoffFactor",
            "baseName": "BackoffFactor",
            "type": "number",
            "format": ""
        },
        {
            "name": "downloadID",
            "baseName": "DownloadID",
            "type": "number",
            "format": ""
        },
        {
            "name": "undownloadableVideos",
            "baseName": "UndownloadableVideos",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ArchiveRequests200ResponseInner.attributeTypeMap;
    }

    public constructor() {
    }
}

